language: node_js

node_js:
  - lts/*
  - node

script:
  - npm test

after_success:
  - npx codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
